Models/Screen.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Gather_Requirement_Project.Models
{
    public class Screen
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [Required]
        public string EmpName { get; set; }

        //[Required]
        public string DevName { get; set; }

        //[Required]
        public DateTime Date { get; set; }

        [Required]
        public string ScreenName { get; set; }


        [Required]
        public string ScreenNameArabic { get; set; }


        [Required]
        public string EmpJob { get; set; }

        //[Required]
        //public string Criteria { get; set; }

        //[Required]
        //public string PreCondition { get; set; }

        //[Required]
        //public string DoSceniro { get; set; }

        //[Required]
        //public string ExpectedResult { get; set; }

        //[Required]
        //public string ScreenGoal { get; set; }

        
        public string ImagePathPhysical { get; set; }
        public string ImageName { get; set; }

        [NotMapped]
        public IFormFile ImageFile { get; set; }




        [ForeignKey("ScreenTypes")]
        public int screenTypeID { get; set; }
        public virtual ScreenType ScreenTypes { get; set; }


        [ForeignKey("Module")]
        public int ModuleID { get; set; }
        public virtual Module Module { get; set; }


        public virtual ICollection<ScreenComponent> ScreenComponents { get; set; }
        public virtual ICollection<UserStories> UserStories { get; set; }
    }
}

Models/ScreenType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Gather_Requirement_Project.Models
{
    public class ScreenType
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Screen> Screens { get; set; }
    }
}

Controllers/ScreenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Gather_Requirement_Project.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.IO;
using Microsoft.Net.Http.Headers;
using System.Text;
using Microsoft.Office.Interop.Word;
using Microsoft.Extensions.Configuration;
using System.Drawing;
using Microsoft.AspNetCore.Authorization;
using Gather_Requirement_Project.Models.JsonClasses;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.Extensions.Hosting;

namespace Gather_Requirement_Project.Controllers
{
    [Authorize]
    public class ScreenController : Controller
    {

        public IConfiguration Configuration { get; }
        Context context;
        private readonly IHostingEnvironment _hostingEnvironment;

        public ScreenController(Context _context, IConfiguration configuration, IHostingEnvironment hostingEnvironment)
        {
            context = _context;
            Configuration = configuration;
            _hostingEnvironment = hostingEnvironment;
        }


        // GET: Screen
        public ActionResult Index(int? modulId)
        {
            IEnumerable<ScreenType> ScreenTypeList = context.ScreenTypes.ToList();
            ViewBag.ScreenType = ScreenTypeList;

            IQueryable<Screen> screens = context.Screens.Include(s => s.Module);

            if (modulId != null)
                screens = screens.Where(s => s.ModuleID == modulId);

            ViewBag.ModID = modulId;



            return View(screens.ToList());
        }

        // GET: Screen/Details/5
        public ActionResult Details(int id)
        {
            Screen screenlist = context.Screens.FirstOrDefault(s => s.ID == id);

            IEnumerable<ScreenType> ScreenTypeList = context.ScreenTypes.ToList();
            ViewBag.ScreenType = ScreenTypeList;

            IEnumerable<Module> ProgramList = context.Modules.ToList();
            ViewBag.Program = ProgramList;

            return View(screenlist);
        }

        // GET: Screen/Create
        public ActionResult Create(int modulId)
        {
            IEnumerable<ScreenType> screenTypes = context.ScreenTypes.ToList();
            ViewBag.screenTypesList = screenTypes;

            IEnumerable<Module> modules = context.Modules.Where(s => s.ID == modulId).ToList();
            ViewBag.modulesList = modules;

            ViewBag.ModuleID = modulId;

            return View();
        }

        // POST: Screen/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Screen collection)
        {
            try
            {
                if (collection.ImageFile != null)
                {
                    string FileName = Path.GetFileNameWithoutExtension(collection.ImageFile.FileName);
                    string FileExtension = Path.GetExtension(collection.ImageFile.FileName);
                    FileName = FileName.Trim() + "_" + DateTime.Now.ToString("yyyyMMdd") + FileExtension;
                    //collection.ImagePathPhysical = Configuration.GetSection("Data").GetSection("PhysicalPath").Value + "\\" + FileName;
                    collection.ImagePathPhysical = _hostingEnvironment.ContentRootPath + "\\wwwroot\\Images\\" + FileName;

                    collection.ImageName = FileName;
                    if (collection.ImageFile.Length > 0)
                    {
                        using (var stream = new FileStream(collection.ImagePathPhysical, FileMode.Create))
                        {
                            collection.ImageFile.CopyTo(stream);
                        }
                    }
                }
                IEnumerable<ScreenType> screenTypes = context.ScreenTypes.ToList();
                ViewBag.screenTypesList = screenTypes;

                IEnumerable<Module> modules = context.Modules.Where(s => s.ID == collection.ModuleID).ToList();
                ViewBag.modulesList = modules;

                context.Screens.Add(collection);
                context.SaveChanges();

                return RedirectToAction(nameof(Index), new { modulId = collection.ModuleID });
            }
            catch (Exception ex)
            {
                IEnumerable<ScreenType> screenTypes = context.ScreenTypes.ToList();
                ViewBag.screenTypesList = screenTypes;

                IEnumerable<Module> customerPrograms = context.Modules.ToList();
                ViewBag.programList = customerPrograms;
                return View();
            }
        }

        // GET: Screen/Edit/5
        public ActionResult Edit(int id)
        {
            Screen ScreenEdit = context.Screens.FirstOrDefault(s => s.ID == id);

            //Dpartment
            IEnumerable<ScreenType> screenTypes = context.ScreenTypes.ToList();
            ViewBag.screenTypesList = screenTypes;

            IEnumerable<Module> modules = context.Modules.ToList();
            ViewBag.modules = modules;

            return View(ScreenEdit);
        }

        // POST: Screen/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Screen collection)
        {
            try
            {
                Screen screenInDb = context.Screens.FirstOrDefault(s => s.ID == id);

                if (collection.ImageFile != null)
                {
                    string FileName = Path.GetFileNameWithoutExtension(collection.ImageFile.FileName);
                    string FileExtension = Path.GetExtension(collection.ImageFile.FileName);
                    FileName = FileName.Trim() + "_" + DateTime.Now.ToString("yyyyMMdd") + FileExtension;
                    //screenInDb.ImagePathPhysical = Configuration.GetSection("Data").GetSection("PhysicalPath").Value + "\\" + FileName;
                    screenInDb.ImagePathPhysical = _hostingEnvironment.ContentRootPath + "\\wwwroot\\Images\\" + FileName;
                    screenInDb.ImageName = FileName;
                    if (collection.ImageFile.Length > 0)
                    {
                        using (var stream = new FileStream(screenInDb.ImagePathPhysical, FileMode.Create))
                        {
                            collection.ImageFile.CopyTo(stream);
                        }
                    }
                }

                screenInDb.EmpName = collection.EmpName;
                //screenInDb.DevName = collection.DevName;
                //screenInDb.Date = collection.Date;
                screenInDb.ScreenName = collection.ScreenName;
                screenInDb.ScreenNameArabic = collection.ScreenNameArabic;
                screenInDb.screenTypeID = collection.screenTypeID;
                screenInDb.EmpJob = collection.EmpJob;

                context.SaveChanges();
                return RedirectToAction(nameof(Index), new { modulId = collection.ModuleID });
            }
            catch
            {
                //Screen screenInDb = context.Screens.FirstOrDefault(s => s.ID == id);
                IEnumerable<ScreenType> screenTypes = context.ScreenTypes.ToList();
                ViewBag.screenTypesList = screenTypes;

                IEnumerable<Module> customerPrograms = context.Modules.ToList();
                ViewBag.programList = customerPrograms;


                return View();
            }
        }

        // GET: Screen/Delete/5
        public ActionResult Delete(int id)
        {
            Screen screen = context.Screens.FirstOrDefault(s => s.ID == id);

            context.Screens.Remove(screen);
            context.SaveChanges();
            return RedirectToAction(nameof(Index), new { modulId = screen.ModuleID });
        }

        // POST: Screen/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }




        public ActionResult GenerateTXT(int id)
        {
            Screen ScreenObject = context.Screens.FirstOrDefault(s => s.ID == id);
            IEnumerable<ScreenComponent> ScreenComponents = context.ScreenComponent.Where(s => s.ScreenID == ScreenObject.ID);
            /*
            string lines;
            lines = "This is test document " + "\n";
            lines += "As a <" + ScreenObject.EmpJob + "> " + "\n";
            lines += "I want to <" + ScreenObject.ScreenName + "> " + "\n";
            lines += "So that, <" + ScreenObject.ScreenGoal + "> " + "\n";
            lines += "User Story" + "\n";
            lines += " " + "\n";
            lines += "This is test document " + "\n";
            lines += "Acceptance Criteria: " + ScreenObject.Criteria + "\n";
            lines += "Given <" + ScreenObject.PreCondition + "> " + "\n";
            lines += "When <" + ScreenObject.DoSceniro + "> " + "\n";
            lines += "Then <" + ScreenObject.ExpectedResult + "> " + "\n";
            lines += " " + "\n";
            lines += " " + "\n";
            lines += "FieldnameE FieldnameA  Fieldtype   Validation  Note" + "\n";
            

            string[] s1 = new string[20];
            string[] s2 = new string[20];
            int i = 0;
            string val = "";

            foreach (ScreenComponent ScreenComponent in ScreenComponents)
            {
                val = "";

                lines += ScreenComponent.FieldNameEnglish;
                lines += "    ";
                lines += ScreenComponent.FielNameArabic;
                lines += "    ";
                FieldType fieldType = context.FieldTypes.FirstOrDefault(s => s.ID == ScreenComponent.FieldTypeID);
                lines += (fieldType.Name.ToString()) ?? " ";
                lines += "    ";

Views/Screen/Create.cshtml
@model Gather_Requirement_Project.Models.Screen
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager;

@{
    ViewData["Title"] = "Create";

    SelectList ScreentTypeList = new SelectList(ViewBag.screenTypesList, "ID", "Name", ViewBag.screenTypesList);
    SelectList ModulesList = new SelectList(ViewBag.modulesList, "ID", "EnglishNameInSingle", ViewBag.modulesList);

}


<div class="container-fluid" id="page-top">
    <div class="card ">
        <div class="card-header">
            <h4>  <i class="fa fa-desktop" aria-hidden="true"></i>&nbsp&nbsp Create New Screen </h4>
        </div>
        <div class="card-body" style="">
            <div class="row">
                <div class="col-md-10">

                </div>
                <div class="col-md-2">
                    <a asp-action="Index" asp-route-modulId="@ViewBag.ModuleID">Go to Back</a>
                </div>
            </div>
            <hr />
            <div class="text-md-left row">

                <form asp-action="Create" asp-controller="Screen" method="post" enctype="multipart/form-data" class="col-md-12">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div>

                                    <label class="form-label-group" asp-for="ScreenName"><b>Screen Name</b></label>
                                    <input asp-for="ScreenName" class="form-control" />
                                    <span asp-validation-for="ScreenName" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div>

                                    <label class="form-label-group" asp-for="ScreenNameArabic"><b>Screen Name Arabic</b></label>
                                    <input asp-for="ScreenNameArabic" class="form-control" />
                                    <span asp-validation-for="ScreenNameArabic" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div>
                                    <label class="form-label-group" asp-for="ModuleID"><b>Module</b></label><br />
                                    <select id="sel" hidden asp-for="ModuleID" class="form-control" asp-items="ModulesList"></select>
                                    <label id="lbl" class="form-label-group"></label>

                                </div>
                            </div>

                            <div class="col-md-6">
                                <div>
                                    <label class="form-label-group" asp-for="screenTypeID"><b>Screen Type</b></label>
                                    <select asp-for="screenTypeID" class="form-control" asp-items="ScreentTypeList"></select>
                                </div>
                            </div>




                            <div class="col-md-6">
                                <div>
                                    <label class="form-label-group" asp-for="EmpName" class="control-label"><b>Employee Name</b></label>
                                    <input asp-for="EmpName" class="form-control" />
                                    <span asp-validation-for="EmpName" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div>
                                    <label class="form-label-group" asp-for="EmpJob" class="control-label"><b>Employee Job</b></label>
                                    <input asp-for="EmpJob" class="form-control" />
                                    <span asp-validation-for="EmpJob" class="text-danger"></span>
                                </div>
                            </div>

                            @*<div class="col-md-6">
                                <div>
                                    <label class="form-label-group" asp-for="DevName" class="control-label"><b>Developer Name</b></label>
                                    <input asp-for="DevName" class="form-control" value="@User.Identity.Name" />
                                    <span asp-validation-for="DevName" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div>
                                    <label class="form-label-group" asp-for="Date" class="control-label"><b>Date</b>  </label>
                                    <input asp-for="Date" class="form-control" type="Date" />
                                    <span asp-validation-for="Date" class="text-danger"></span>
                                </div>
                            </div>*@






                            <div class="col-md-6">
                                <div>
                                    <label class="form-label-group" asp-for="ImagePathPhysical"><b>Upload Image</b></label>
                                    <input class="form-control" type="file" asp-for="ImageFile" />
                                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                                </div>
                            </div>


                            <div class="col-md-12" style="margin-top:15px">
                                <div class="form-label-group" style="float:left">
                                    <input type="submit" value="Create" class="btn btn-primary" style="padding:10px;text-align:center;font-weight:bold" />
                                </div>
                            </div>
                        </div>
                    </div>

                </form>

            </div>


        </div>
    </div>
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>
    $(document).ready(function () {
        $("#lbl").empty();
        $("#lbl").append(($("#sel").children("option:selected").text()));
    });
</script>

Views/Screen/Details.cshtml
@model Gather_Requirement_Project.Models.Screen

@{
    ViewData["Title"] = "Details";
    //string str = "~/Images/" + "20190803-Screenshot_25.png";
}

<div class="container-fluid">
    <div class="card mb-3  border">
      
        <div class="row card-header">
            <div class="col-md-10">
                <h4>  <i class="fa fa-desktop" aria-hidden="true"></i>&nbsp&nbsp Details of Screen </h4>
            </div>
            <div class="col-md-2">
                <a asp-action="Index" asp-route-modulId="@Model.ModuleID" >Go to Back</a>
            </div>
        </div>

        <div class="card-body" style="">
            <div class="row">
                <div class="col-md-10">

                </div>

                <div class="col-md-2">
                    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a>

                </div>
            </div>
            <hr />
            <dl class="text-md-left   table-bordered table-hover row">

                <dt class="col-sm-3">
                    <span>Screen Name</span>
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.ScreenName)
                </dd>

                <dt class="col-sm-3">
                    <span>Screen Name Arabic</span>
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.ScreenNameArabic)
                </dd>

                <dt class="col-sm-3">
                    <span>Program of Screen</span>
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Module.EnglishNameInSingle)
                </dd>

                <dt class="col-sm-3">

                    <span>Screen Type</span>
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.ScreenTypes.Name)
                </dd>

                @*<dt class="col-sm-3">
            <span>Screen Goal</span>
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.ScreenGoal)
        </dd>*@

                <dt class="col-sm-3">
                    <span>Employee Name</span>
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.EmpName)
                </dd>

                <dt class="col-sm-3">
                    <span> Employee Job</span>
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.EmpJob)
                </dd>

                @*<dt class="col-sm-3">
                    <span>Developer Name</span>
                </dt>
               <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.DevName)
                </dd>
                <dt class="col-sm-2">
                    <span>Date</span>
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Date)
                </dd>*@
 


                <dt class="col-sm-3">
                    <span>Image For Screen</span>
                </dt>
                <dd class="col-sm-9">
                    @*@Html.DisplayFor(model => model.ImageName)*@ <br />
                    <img src="~/Images/@Html.DisplayFor(model => model.ImageName)" alt="Image" style="height:70px;width:70px;" />
                </dd>



            </dl>
        </div>

    </div>
        
    </div>

Views/Screen/Edit.cshtml
@model Gather_Requirement_Project.Models.Screen

@{
    ViewData["Title"] = "Edit";

    SelectList ScreentTypeList = new SelectList(ViewBag.screenTypesList, "ID", "Name", ViewBag.screenTypesList);

    SelectList ModulesList = new SelectList(ViewBag.modules, "ID", "EnglishNameInSingle", ViewBag.modules);
}

<div class="container-fluid" id="page-top">
    <div class="card ">
        <div class="card-header">
            <h4>  <i class="fa fa-desktop" aria-hidden="true"></i>&nbsp&nbsp Edit Screen </h4>
        </div>
        <div class="card-body" style="">
            <div class="row">
                <div class="col-md-10">

                </div>
                <div class="col-md-2">
                    <a asp-action="Index" asp-route-modulId="@Model.ModuleID" >Go to Back</a>
                </div>
            </div>
            <hr />
            <div class="text-md-left row">

                <form asp-action="Edit" asp-controller="Screen" method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="ID" />

                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div>

                                    <label asp-for="ScreenName" class="control-label"><b>Screen Name</b></label>
                                    <input asp-for="ScreenName" class="form-control" />
                                    <span asp-validation-for="ScreenName" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div>

                                    <label asp-for="ScreenNameArabic" class="control-label"><b>Screen Name Arabic</b></label>
                                    <input asp-for="ScreenNameArabic" class="form-control" />
                                    <span asp-validation-for="ScreenNameArabic" class="text-danger"></span>
                                </div>
                            </div>
                            @*<div class="col-md-6">
            <div>
                @Html.LabelFor(model => model.CustomerProgramID, "Program For This Screen ")
                <div class="col-md-12">
                    @foreach (var item in ViewBag.programList)
                    {
                        if (item.ID == Model.CustomerProgramID)
                        {
                            @Html.DropDownList("CustomerProgramID", ProgramList)

                        }

                    }

                </div>
            </div>
        </div>*@

                            <div class="col-md-6">
                                <div>
                                    <label class="form-label-group" asp-for="ModuleID"><b>Module</b></label><br />
                                    <select id="sel" hidden asp-for="ModuleID" class="form-control" asp-items="ModulesList"></select>
                                    <label id="lbl" class="form-label-group"></label>
                                </div>
                            </div>

                            @*<div class="col-md-6">
            <div>
                @Html.LabelFor(model => model.screenTypeID, "Screen Type")
                <div class="col-md-2">
                    @foreach (var item in ViewBag.screenTypesList)
                    {
                        if (item.ID == Model.screenTypeID)
                        {
                            @Html.DropDownList("ScreenTypeID", ScreentTypeList)

                        }

                    }

                </div>
            </div>
        </div>*@

                            <div class="col-md-6">
                                <div>
                                    <label class="form-label-group" asp-for="screenTypeID"><b>Screen Type</b></label>
                                    <select asp-for="screenTypeID" class="form-control" asp-items="ScreentTypeList"></select>
                                </div>
                            </div>




                            @*<div class="col-md-6">
            <div>
                <label asp-for="ScreenGoal" class="control-label"><b>Screen Goal</b></label>
                <input asp-for="ScreenGoal" class="form-control" />
                <span asp-validation-for="ScreenGoal" class="text-danger"></span>
            </div>
        </div>*@

                            <div class="col-md-6">
                                <div>
                                    <label asp-for="EmpName" class="control-label"><b>Employee Name</b></label>
                                    <input asp-for="EmpName" class="form-control" />
                                    <span asp-validation-for="EmpName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div>
                                    <label asp-for="EmpJob" class="control-label"><b>Employee Job</b></label>
                                    <input asp-for="EmpJob" class="form-control" />
                                    <span asp-validation-for="EmpJob" class="text-danger"></span>
                                </div>
                            </div>
                            @*<div class="col-md-6">
                                <div>
                                    <label asp-for="DevName" class="control-label"><b>Developer Name</b></label>
                                    <input asp-for="DevName" class="form-control" />
                                    <span asp-validation-for="DevName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div>
                                    <label asp-for="Date" class="control-label"><b>Date</b></label>
                                    <input asp-for="Date" class="form-control" />
                                    <span asp-validation-for="Date" class="text-danger"></span>
                                </div>
                            </div>*@
                            @*<div class="col-md-6">
           <div>
                <label asp-for="Criteria" class="control-label"><b>Criteria</b></label>
                <textarea asp-for="Criteria" class="form-control" cols="5" rows="10"></textarea>
                <span asp-validation-for="Criteria" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-6">
            <div>
                <label asp-for="PreCondition" class="control-label"><b>PreCondition</b></label>
                <textarea asp-for="PreCondition" class="form-control" cols="5" rows="10"></textarea>
                <span asp-validation-for="PreCondition" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-6">
            <div>
                <label asp-for="DoSceniro" class="control-label"><b>Sceniro</b></label>
                <textarea asp-for="DoSceniro" class="form-control" cols="5" rows="10"></textarea>
                <span asp-validation-for="DoSceniro" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-6">
            <div>
                <label asp-for="ExpectedResult" class="control-label"> <b>Expected Result</b></label>
                <textarea asp-for="ExpectedResult" class="form-control" cols="5" rows="10"></textarea>
                <span asp-validation-for="ExpectedResult" class="text-danger"></span>
            </div>
        </div>*@
                            <br />
                            <div class="col-md-6">
                                <div>
                                    <label class="form-label-group"><b>Upload Image</b></label>
                                    <label class="control-label">:  @Model.ImageName</label>
                                    <input class="form-control" type="file" asp-for="ImageFile" />
                                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                                </div>
                            </div>


                            <div class="col-md-12" style="margin-top:15px">
                                <div class="form-label-group" style="float:left">
                                    <input type="submit" value="Save Changes" class="btn btn-primary" />
                                </div>
                            </div>


</form>
            </div>
        </div>
    </div>
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
</div>





@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script>
    $(document).ready(function () {
        $("#lbl").empty();
        $("#lbl").append( ($("#sel").children("option:selected").text()) );
    });
</script>