Models/Module.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Gather_Requirement_Project.Models
{
    public class Module
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string EnglishNameInSingle { get; set; }
        public string EnglishNameInPlural { get; set; }
        public string ArabicNameInSingle { get; set; }
        public string ArabicNameInPlural { get; set; }
        //[Url(ErrorMessage = "Please insert a valid URL")]
        public string URLForService { get; set; }


        [ForeignKey("CustomerProgram")]
        public int CustomerProgramID { get; set; }
        public CustomerProgram CustomerProgram { get; set; }

        public virtual ICollection<Screen> Screens { get; set; }

    }
}

Controllers/ModulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Gather_Requirement_Project.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.Net.Http.Headers;
using System.Text;
using Gather_Requirement_Project.Models.SQLScript;
using System.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Pluralize.NET.Core;



namespace Gather_Requirement_Project.Controllers
{
    [Authorize]

    public class ModulesController : Controller
    {
        public IConfiguration Configuration { get; }

        Context context;
        private readonly IHostingEnvironment _hostingEnvironment;

        public ModulesController(Context _context, IConfiguration configuration, IHostingEnvironment hostingEnvironment)
        {
            context = _context;
            Configuration = configuration;
            _hostingEnvironment = hostingEnvironment;

        }


        public ActionResult Index(int? programId)
        {
            IQueryable<Module> module = context.Modules.Include(s => s.CustomerProgram);

            if (programId != null)
                module = module.Where(s => s.CustomerProgramID == programId);

            ViewBag.ProID = (programId);

            return View(module.ToList());
        }

        public ActionResult Details(int id)
        {
            Module moduleslist = context.Modules.FirstOrDefault(s => s.ID == id);

            IEnumerable<Screen> ScreenList = context.Screens.ToList();
            ViewBag.screenList = ScreenList;

            return View(moduleslist);
        }

        public ActionResult Create(int? programId)
        {
            IEnumerable<CustomerProgram> customerPrograms = context.CustomerPrograms.ToList();
            ViewBag.programList = customerPrograms;

            ViewBag.ProID = programId;


            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Module collection)
        {
            try
            {
                context.Modules.Add(collection);
                context.SaveChanges();

                return RedirectToAction(nameof(Index), new { programId = collection.CustomerProgramID });
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            IEnumerable<CustomerProgram> customerPrograms = context.CustomerPrograms.ToList();
            ViewBag.programList = customerPrograms;

            Module moduleEdit = context.Modules.FirstOrDefault(s => s.ID == id);
            return View(moduleEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Module collection)
        {
            try
            {
                context.Entry(collection).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction(nameof(Index), new { programId = collection.CustomerProgramID });
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            Module module = context.Modules.FirstOrDefault(s => s.ID == id);

            context.Modules.Remove(module);
            context.SaveChanges();
            return RedirectToAction(nameof(Index), new { programId = module.CustomerProgramID });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }







        private string GenerateSQLtext(IEnumerable<Screen> Screens, Module ModuleObject)
        {
            string fill;
            string[] s1 = new string[100];
            string[] s2 = new string[100];
            int i = 0;

            Queries queries = new Queries();
            fill = queries.DB(ModuleObject.EnglishNameInSingle);


            foreach (var Screen in Screens)
            {
                ScreenType screenType = context.ScreenTypes.FirstOrDefault(s => s.ID == Screen.screenTypeID);
                if (screenType.Name.ToLower() == "create")
                {
                    IEnumerable<ScreenComponent> ScreenComponents = context.ScreenComponent.Where(s => s.ScreenID == Screen.ID);
                    //if(ScreenComponents.Count() != 0)
                    //{
                    s1 = new string[ScreenComponents.Count()];
                    s2 = new string[ScreenComponents.Count()];
                    i = 0;

                    foreach (var ScreenComponent in ScreenComponents)
                    {

                        FieldType inputType = context.FieldTypes.FirstOrDefault(s => s.ID == ScreenComponent.FieldTypeID);
                        string name = inputType.Name;
                        if (name == "button")
                            continue;
                        s1[i] = ScreenComponent.FieldNameEnglish;


                        switch (name.ToLower())
                        {
                            case "dropdown": name = "int"; break;
                            case "number": name = "nvarchar(255)"; break;
                            case "text": name = "nvarchar(255)"; break;
                            case "email": name = "nvarchar(255)"; break;
                            case "radibutton": name = "nvarchar(255)"; break;
                            case "textarea": name = "nvarchar(255)"; break;
                            case "file": name = "nvarchar(255)"; break;
                            case "checkbox": name = "boolean"; break;
                            case "date": name = "datetime"; break;
                            default: name = ""; break;
                        }

                        s2[i] = name;

                        i++;
                    }

                    fill += queries.CreateTable(Screen.ScreenName, s1, s2);
                    //}
                }
            }
            return fill;
        }
        public FileStreamResult GenerateSQL(int? id)
        {
            Module ModuleObject = context.Modules.FirstOrDefault(s => s.ID == id);
            IEnumerable<Screen> Screens = context.Screens.Where(s => s.ModuleID == ModuleObject.ID);
            string ss = "";
            if (Screens.Count() != 0)
                ss = GenerateSQLtext(Screens, ModuleObject);

            var stream = new MemoryStream(Encoding.UTF8.GetBytes(ss));
            return new FileStreamResult(stream, new MediaTypeHeaderValue("text/plain"))
            {
                FileDownloadName = ModuleObject.EnglishNameInSingle + ".txt"
            };
        }
        public FileStreamResult GenerateSQLAll()
        {
            IEnumerable<Module> ModuleObjects = context.Modules.ToList();
            string str = "";
            foreach (var module in ModuleObjects)
            {
                IEnumerable<Screen> Screens = context.Screens.Where(s => s.ModuleID == module.ID);
                if (Screens != null)
                    str += GenerateSQLtext(Screens, module);
                str += "\n\n\n";
            }

            var stream = new MemoryStream(Encoding.UTF8.GetBytes(str));
            return new FileStreamResult(stream, new MediaTypeHeaderValue("text/plain"))
            {
                FileDownloadName = "DBScrpit" + ".txt"
            };
        }
        public async Task<IActionResult> Backup(string DBname = "")
        {
            string DBname1 = Configuration.GetSection("Data").GetSection("DBName").Value; ;
            string queryString1 = "BACKUP DATABASE [" + DBname1 + "] TO DISK = '" + Configuration.GetSection("Data").GetSection("Path1").Value + "\\" + DBname1 + ".bak';";
            string connectionString = Configuration.GetConnectionString("SqlConnection");

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                SqlCommand command = new SqlCommand(queryString1, connection);
                connection.Open();
                SqlDataReader reader = command.ExecuteReader();
            }

            string filename = DBname1 + ".bak";
            if (filename == null)
                return Content("filename not present");

            var path = Path.Combine(Configuration.GetSection("Data").GetSection("Path1").Value, filename);

            var memory = new MemoryStream();
            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory, "text/plain", Path.GetFileName(path));

        }


        // generate Lookup
        private string LowercaseFirst(string s)
        {
            if (string.IsNullOrEmpty(s))
            {
                return string.Empty;
            }
            char[] a = s.ToCharArray();
            a[0] = char.ToLower(a[0]);
            return new string(a);
        }
        private string LookupModelFile(string name)
        {
            string file = @"
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LookUpTable.Models
{
    public class Pattern1
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
    }
}
";
            return file.Replace("Pattern1", name);
        }
        private string LookupControlFile(string name)
        {
            string file = @"
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LookUpTable.DAL;

Views/Modules/Create.cshtml
@model Gather_Requirement_Project.Models.Module

@{
    ViewData["Title"] = "Create";
    SelectList ProgramList = new SelectList(ViewBag.programList, "ID", "EnglishNameInSingle",ViewBag.ProID);

}

<div class="container">
    <div class="card ">
        <div class="card-header">
            <h4> <i class="fa fa-address-card-o" aria-hidden="true"></i>&nbsp&nbsp Create New Module </h4>
        </div>
        <div class="card-body" style="">
            <div class="row">
                <div class="col-md-10">

                </div>
                <div class="col-md-2">
                    <a asp-action="Index">Go to Back</a>
                </div>
            </div>
            <hr />

            <div class="text-md-left row">
                <div class="col-md-4">
                    <form asp-action="Create" asp-controller="Modules" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="form-group">
                            <label class="form-dropdown-group" asp-for="CustomerProgramID"><b>Program</b></label><br />
                            <select id="sel" hidden asp-for="CustomerProgramID" class="form-control" asp-items="ProgramList"></select>
                            <label id="lbl" class="form-label-group"></label>

                        </div>

                        <div class="form-group">
                            <label asp-for="EnglishNameInSingle" class="control-label">Module English Name In Single</label>
                            <input asp-for="EnglishNameInSingle" class="form-control" />
                            <span asp-validation-for="EnglishNameInSingle" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="EnglishNameInPlural" class="control-label">Module English Name In Plural</label>
                            <input asp-for="EnglishNameInPlural" class="form-control" />
                            <span asp-validation-for="EnglishNameInPlural" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="ArabicNameInSingle" class="control-label">Module Arabic Name In Single</label>
                            <input asp-for="ArabicNameInSingle" class="form-control" />
                            <span asp-validation-for="ArabicNameInSingle" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="ArabicNameInPlural" class="control-label">Module Arabic Name In Plural</label>
                            <input asp-for="ArabicNameInPlural" class="form-control" />
                            <span asp-validation-for="ArabicNameInPlural" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="URLForService" class="control-label">Module URL For Service</label>
                            <input asp-for="URLForService" class="form-control" />
                            <span asp-validation-for="URLForService" class="text-danger"></span>
                        </div>


                        <div class="form-group">
                            <input type="submit" value="create" class="btn btn-primary" />
                        </div>


                    </form>
                </div>
            </div>


        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script>
    $(document).ready(function () {
        $("#lbl").empty();
        $("#lbl").append( ($("#sel").children("option:selected").text()) );
    });
</script>

Views/Modules/Delete.cshtml
@model Gather_Requirement_Project.Models.Module

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Module</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EnglishNameInSingle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EnglishNameInSingle)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Modules/Details.cshtml
@model Gather_Requirement_Project.Models.Module

@{
    ViewData["Title"] = "Details";
}

<div class="card ">
    <div class="card-header">
        <h4> <i class="fas fa-table"></i>&nbsp&nbsp Details Module </h4>
    </div>
    <div class="card-body" style="">
        <div class="row">
            <div class="col-md-10">

            </div>
            <div class="col-md-2">
                <a asp-action="Index" asp-route-programId="@Model.CustomerProgramID">Go to Back</a>
            </div>
        </div>
        <hr />



        <dl class="text-md-left  row">
            <dt class="col-sm-3">
                <span>Module English Name In Single</span>
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.EnglishNameInSingle)
            </dd>

            <dt class="col-sm-3">
                <span>Module English Name In Plural</span>
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.EnglishNameInPlural)
            </dd>

            <dt class="col-sm-3">
                <span>Module Arabic Name In Single</span>
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.ArabicNameInSingle)
            </dd>


            <dt class="col-sm-3">
                <span>Module Arabic Name In Plural</span>
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.ArabicNameInPlural)
            </dd>


            <dt class="col-sm-3">
                <span>Module URL For Service</span>
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.URLForService)
            </dd>

        </dl>


        <dl class="col-sm-5">
            <b><a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> </b>
        </dl>



    </div>
    <div>
       
        
    </div>
    </div>

Views/Modules/Edit.cshtml
@model Gather_Requirement_Project.Models.Module

@{
    ViewData["Title"] = "Edit";
        SelectList ProgramList = new SelectList(ViewBag.programList, "ID", "EnglishNameInSingle", ViewBag.programList);

}
<div class="card ">
    <div class="card-header">
        <h4> <i class="fas fa-table"></i>&nbsp&nbsp EditProgram </h4>
    </div>
    <div class="card-body" style="">
        <div class="row">
            <div class="col-md-10">

            </div>
            <div class="col-md-2">
                <a asp-action="Index" asp-route-programId="@Model.CustomerProgramID" >Go to Back</a>
            </div>
        </div>
        <hr />

        <div class="text-md-left row">
            <div class="col-md-6 jumbotron">
                <form asp-action="Edit" asp-controller="Modules" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="ID" />

                    <div class="form-group">
                        <label class="form-dropdown-group" asp-for="CustomerProgramID"><b>Program</b></label><br />
                        <select id="sel" hidden asp-for="CustomerProgramID" class="form-control" asp-items="ProgramList"></select>
                        <label id="lbl" class="form-label-group"></label>
                        <span asp-validation-for="CustomerProgramID" class="text-danger"></span>
                        <br />

                        <label asp-for="EnglishNameInSingle" class="control-label">Module English Name In Single</label>
                        <input asp-for="EnglishNameInSingle" class="form-control" />
                        <span asp-validation-for="EnglishNameInSingle" class="text-danger"></span>
                        <br />

                        <label asp-for="EnglishNameInPlural" class="control-label">Module English Name In Plural</label>
                        <input asp-for="EnglishNameInPlural" class="form-control" />
                        <span asp-validation-for="EnglishNameInPlural" class="text-danger"></span>
                        <br />

                        <label asp-for="EnglishNameInSingle" class="control-label">Module Arabic Name In Single</label>
                        <input asp-for="ArabicNameInSingle" class="form-control" />
                        <span asp-validation-for="ArabicNameInSingle" class="text-danger"></span>
                        <br />

                        <label asp-for="EnglishNameInPlural" class="control-label">Module Arabic Name In Plural</label>
                        <input asp-for="ArabicNameInPlural" class="form-control" />
                        <span asp-validation-for="ArabicNameInPlural" class="text-danger"></span>


                        <label asp-for="URLForService" class="control-label">Module URL For Service</label>
                        <input asp-for="URLForService" class="form-control" />
                        <span asp-validation-for="URLForService" class="text-danger"></span>
                        <br />



                    </div>

                    <div class="form-group">
                        <input type="submit" value="حفظ التعديل" class="btn btn-primary" />
                    </div>

                </form>
            </div>
        </div>


    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script>
    $(document).ready(function () {
        $("#lbl").empty();
        $("#lbl").append( ($("#sel").children("option:selected").text()) );
    });
</script>

Views/Modules/Index.cshtml
@model IEnumerable<Gather_Requirement_Project.Models.Module>

@{
    ViewData["Title"] = "Index";
    int var = 1;

}


<div class="container-fluid">
    <div class="card mb-3">
        <div class="card-header ">
            <h4> <i class="fa fa-address-card-o" aria-hidden="true"></i>&nbsp&nbsp Module </h4>

        </div>

        <div class="card-body" style="">
            <div class="row">
                <div class="col-md-10">
                    <a asp-action="Create" asp-route-programId='@ViewBag.ProID'>New Module</a>
                </div>
                <div class="col-md-2">
                    <a asp-controller="CustomerPrograms" asp-action="Index">Go to Back</a>
                </div>
            </div>
            <hr />


            <table class="table  table-bordered table-hover  table-responsive" id="dataTable">
                <thead>
                    <tr>
                        <th>
                            <span>#</span>
                        </th>
                        <th>
                            <span>Module Name in English</span>
                        </th>
                        <th>
                            <span>Module Name in Arabic</span>
                        </th>
                        <th>
                            <span>Screens</span>
                        </th>
                        <th>
                            <span> </span>
                        </th>
                        <th>
                            <span> Lookup </span>
                        </th>
                        <th>
                            <span> CopyIT </span>
                        </th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {

                        <tr>
                            <td>
                                @var
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.EnglishNameInSingle)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ArabicNameInSingle)
                            </td>

                            <td>
                                <a asp-controller="Screen" asp-action="Index" asp-route-modulId="@item.ID" class="btn btn-warning"><i class="fa fa-desktop"></i></a>
                            </td>


                            <td>
                                <a asp-action="Edit" asp-route-id="@item.ID" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                                <a asp-action="Details" asp-route-id="@item.ID" class="btn btn-info"><i class="fa fa-book"></i></a>
                                <a asp-action="Delete" asp-route-id="@item.ID" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                                @*<a asp-action="GenerateSQL" asp-route-id="@item.ID" class="btn btn-danger"><i class="fa fa-file"></i></a>*@
                                @*<a asp-action="GenerateJson" asp-route-id="@item.ID" class="btn btn-danger"><i class="fa fa-file"></i></a>*@
                            </td>

                            <td>
                                <a asp-action="CreateZipFile2" asp-route-Id="@item.ID" class="btn btn-danger"><i class="fa fa-arrow-circle-up"></i></a>
                            </td>

                            <td>
                                <a asp-action="CopyModule" asp-route-Id="@item.ID" class="btn btn-info"><i class="fa fa-arrow-circle-down"></i></a>
                            </td>


                        </tr>
                        var = var + 1;

                    }
                </tbody>
            </table>


        </div>
    </div>

</div>


<script>
    $(document).scroll(function () {
        localStorage['page'] = document.URL;
        localStorage['scrollTop'] = $(document).scrollTop();
    });

    $(document).ready(function () {
        if (localStorage['page'] == document.URL) {
            $(document).scrollTop(localStorage['scrollTop']);
        }
    });
</script>