Models/CustomerProgram.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Gather_Requirement_Project.Models
{
    public class CustomerProgram
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string EnglishNameInSingle { get; set; }
        public string EnglishNameInPlural { get; set; }
        public string ArabicNameInSingle { get; set; }
        public string ArabicNameInPlural { get; set; }
        public string DevName { get; set; }
        public DateTime Date { get; set; }


        //[Url(ErrorMessage = "Please insert a valid URL")]
        public string URLForService { get; set; }

        public ICollection<Module> Modules { get; set; }



        [ForeignKey("Section")]
        public int? SectionID { get; set; }
        public Section Section { get; set; }


    }
}

Controllers/CustomerProgramsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Gather_Requirement_Project.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.Net.Http.Headers;
using System.Text;
using System.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Authorization;
using System.IO.Compression;
using Microsoft.EntityFrameworkCore;
using Gather_Requirement_Project.Models.NotificationClasses;
using Newtonsoft.Json;
using Microsoft.Office.Interop.Word;
using Microsoft.Extensions.Hosting;
using ICSharpCode.SharpZipLib.Zip;
using Microsoft.AspNetCore.Hosting.Server;
using Pluralize.NET.Core;
using Section = Gather_Requirement_Project.Models.Section;

namespace Gather_Requirement_Project.Controllers
{
    [Authorize]

    public class CustomerProgramsController : Controller
    {
        public IConfiguration Configuration { get; }

        Context context;
        private readonly IHostingEnvironment _hostingEnvironment;

        public CustomerProgramsController(Context _context, IConfiguration configuration, IHostingEnvironment hostingEnvironment)
        {
            context = _context;
            Configuration = configuration;
            _hostingEnvironment = hostingEnvironment;
        }


        public ActionResult Index()
        {
            return View(context.CustomerPrograms.Include(s => s.Section).ToList());
        }

        public ActionResult Details(int id)
        {
            CustomerProgram customprogramslist = context.CustomerPrograms.Include(s => s.Section).FirstOrDefault(s => s.ID == id);

            IEnumerable<Module> ModuleList = context.Modules.ToList();
            ViewBag.screenList = ModuleList;

            return View(customprogramslist);
        }

        public ActionResult Create()
        {
            ViewBag.portalsList = context.Section.ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CustomerProgram collection)
        {
            try
            {
                context.CustomerPrograms.Add(collection);
                context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            ViewBag.portalsList = context.Section.ToList();

            CustomerProgram moduleEdit = context.CustomerPrograms.FirstOrDefault(s => s.ID == id);
            return View(moduleEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, CustomerProgram collection)
        {
            try
            {
                context.Entry(collection).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            CustomerProgram customerProgram = context.CustomerPrograms.FirstOrDefault(s => s.ID == id);

            context.CustomerPrograms.Remove(customerProgram);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }






        public IActionResult GenerateJsonFrontEnd(int id)
        {
            CustomerProgram CP = context.CustomerPrograms.FirstOrDefault(s => s.ID == id);
            IEnumerable<Module> mods = context.Modules.Where(s => s.CustomerProgramID == CP.ID);


            ModuleFrontEnd moduleFrontEnd = new ModuleFrontEnd();
            moduleFrontEnd.id = CP.EnglishNameInSingle;
            moduleFrontEnd.title = CP.ArabicNameInSingle;

            children ch1 = new children(); ch1.id = CP.EnglishNameInSingle + " Program"; ch1.title = "البرامج"; ch1.icon = "apps";
            children ch2 = new children(); ch2.id = CP.EnglishNameInSingle + " Config"; ch2.title = "الأعدادات"; ch2.icon = "build";
            children ch3 = new children(); ch3.id = CP.EnglishNameInSingle + " Report"; ch3.title = "التقارير"; ch3.icon = "assignment";

            foreach (var mod in mods)
            {

                subchildren subch = new subchildren();
                subch.id = mod.EnglishNameInSingle;
                subch.title = mod.ArabicNameInSingle;
                subch.url = "/" + mod.EnglishNameInSingle.Replace(" ", "").ToLower() + "";

                ch1.subchildren.Add(subch);



                IEnumerable<Screen> scs = context.Screens.Where(s => s.ModuleID == mod.ID).Include(st => st.ScreenTypes);
                foreach (var sc in scs)
                {

                    if (sc.ScreenTypes.Name == "Setting")
                    {
                        subchildren subch1 = new subchildren();
                        subch1.id = sc.ScreenName;
                        subch1.title = sc.ScreenNameArabic;
                        subch1.url = "/#";

                        ch2.subchildren.Add(subch1);
                    }

                    else if (sc.ScreenTypes.Name == "Report")
                    {
                        subchildren subch2 = new subchildren();
                        subch2.id = sc.ScreenName;
                        subch2.title = sc.ScreenNameArabic;
                        subch2.url = "/#";

                        ch3.subchildren.Add(subch2);
                    }
                }
            }


            moduleFrontEnd.children.Add(ch1);
            moduleFrontEnd.children.Add(ch2);
            moduleFrontEnd.children.Add(ch3);



            HeadFile headFile = new HeadFile();
            headFile.program.Add(moduleFrontEnd);

            string result = JsonConvert.SerializeObject(headFile);
            result = result.Replace("subchildren", "children").Replace("program", CP.EnglishNameInSingle);
            var stream = new MemoryStream(Encoding.UTF8.GetBytes(result));
            return new FileStreamResult(stream, new MediaTypeHeaderValue("text/plain"))
            {
                FileDownloadName = "ModuleFrontEnd.json"
            };
        }

        //private string GenerateSQLtext(IEnumerable<Module> modules, CustomerProgram CustomerProgramObject)
        //{
        //    string fill;
        //    string[] s1 = new string[100];
        //    string[] s2 = new string[100];
        //    int i = 0;

        //    Queries queries = new Queries();
        //    fill = queries.DB(CustomerProgramObject.EnglishNameInSingle);


        //    foreach (var Module in modules)
        //    {
        //        ModuleType screenType = context.ModuleTypes.FirstOrDefault(s => s.ID == Module.screenTypeID);
        //        if (screenType.Name.ToLower() == "create")
        //        {
        //            IEnumerable<ModuleComponent> ModuleComponents = context.ModuleComponent.Where(s => s.ModuleID == Module.ID);
        //            //if(ModuleComponents.Count() != 0)
        //            //{
        //            s1 = new string[ModuleComponents.Count()];
        //            s2 = new string[ModuleComponents.Count()];
        //            i = 0;

        //            foreach (var ModuleComponent in ModuleComponents)
        //            {

        //                FieldType inputType = context.FieldTypes.FirstOrDefault(s => s.ID == ModuleComponent.FieldTypeID);
        //                string name = inputType.Name;
        //                if (name == "button")
        //                    continue;
        //                s1[i] = ModuleComponent.FieldNameEnglish;


        //                switch (name.ToLower())
        //                {
        //                    case "dropdown": name = "int"; break;
        //                    case "number": name = "nvarchar(255)"; break;
        //                    case "text": name = "nvarchar(255)"; break;
        //                    case "email": name = "nvarchar(255)"; break;
        //                    case "radibutton": name = "nvarchar(255)"; break;
        //                    case "textarea": name = "nvarchar(255)"; break;
        //                    case "file": name = "nvarchar(255)"; break;
        //                    case "checkbox": name = "boolean"; break;
        //                    case "date": name = "datetime"; break;
        //                    default: name = ""; break;
        //                }

        //                s2[i] = name;

        //                i++;
        //            }

        //            fill += queries.CreateTable(Module.ModuleName, s1, s2);
        //            //}
        //        }
        //    }
        //    return fill;
        //}

        //public FileStreamResult GenerateSQL(int? id)
        //{
        //    CustomerProgram CustomerProgramObject = context.CustomerPrograms.FirstOrDefault(s => s.ID == id);
        //    IEnumerable<Module> Modules = context.Modules.Where(s => s.CustomerProgramID == CustomerProgramObject.ID);
        //    string ss = "";
        //    if (Modules.Count() != 0)
        //        ss = GenerateSQLtext(Modules, CustomerProgramObject);

        //    var stream = new MemoryStream(Encoding.UTF8.GetBytes(ss));
        //    return new FileStreamResult(stream, new MediaTypeHeaderValue("text/plain"))
        //    {
        //        FileDownloadName = CustomerProgramObject.EnglishNameInSingle + ".txt"
        //    };
        //}

        //public FileStreamResult GenerateSQLAll()
        //{

Views/CustomerPrograms/Create.cshtml
@model Gather_Requirement_Project.Models.CustomerProgram
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager;

@{
    ViewData["Title"] = "Create";
    SelectList SectionsList = new SelectList(ViewBag.portalsList, "ID", "ArabicName");

}

<div class="container">
    <div class="card ">
        <div class="card-header">
            <h4> <i class="fa fa-address-card-o" aria-hidden="true"></i>&nbsp&nbsp Create New Program </h4>
        </div>
        <div class="card-body" style="">
            <div class="row">
                <div class="col-md-10">

                </div>
                <div class="col-md-2">
                    <a asp-action="Index">Go to Back</a>
                </div>
            </div>
            <hr />

            <div class="text-md-left row">
                <div class="col-md-4">
                    <form asp-action="Create" asp-controller="CustomerProgram" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="form-group">
                            <label asp-for="EnglishNameInSingle" class="control-label">Program English Name In Single</label>
                            <input asp-for="EnglishNameInSingle" class="form-control" />
                            <span asp-validation-for="EnglishNameInSingle" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="EnglishNameInPlural" class="control-label">Program English Name In Plural</label>
                            <input asp-for="EnglishNameInPlural" class="form-control" />
                            <span asp-validation-for="EnglishNameInPlural" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="ArabicNameInSingle" class="control-label">Program Arabic Name In Single</label>
                            <input asp-for="ArabicNameInSingle" class="form-control" />
                            <span asp-validation-for="ArabicNameInSingle" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="ArabicNameInPlural" class="control-label">Program Arabic Name In Plural</label>
                            <input asp-for="ArabicNameInPlural" class="form-control" />
                            <span asp-validation-for="ArabicNameInPlural" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="URLForService" class="control-label">Program URL For Service</label>
                            <input asp-for="URLForService" class="form-control" />
                            <span asp-validation-for="URLForService" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SectionID" class="control-label">Section</label>
                            <select asp-for="SectionID" class="form-control" asp-items="SectionsList">
                                <option disabled selected>--- SELECT ---</option>
                            </select>
                            <span asp-validation-for="SectionID" class="text-danger"></span>
                        </div>

                        <div>
                            <label class="form-label-group" asp-for="DevName" class="control-label"><b>Developer Name</b></label>
                            <input asp-for="DevName" class="form-control" value="@User.Identity.Name" />
                            <span asp-validation-for="DevName" class="text-danger"></span>
                        </div>


                        <br />

                        <div>
                            <label class="form-label-group" asp-for="Date" class="control-label"><b>Date</b>  </label>
                            <input asp-for="Date" class="form-control" type="Date" />
                            <span asp-validation-for="Date" class="text-danger"></span>
                        </div>

                        <br />


                        <div class="form-group">
                            <input type="submit" value="create" class="btn btn-primary" />
                        </div>


                    </form>
                </div>
            </div>


        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CustomerPrograms/Delete.cshtml
@model Gather_Requirement_Project.Models.CustomerProgram

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CustomerProgram</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EnglishNameInSingle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EnglishNameInSingle)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/CustomerPrograms/Details.cshtml
@model Gather_Requirement_Project.Models.CustomerProgram

@{
    ViewData["Title"] = "Details";
}

<div class="card ">
    <div class="card-header">
        <h4> <i class="fas fa-table"></i>&nbsp&nbsp Details Program </h4>
    </div>
    <div class="card-body" style="">
        <div class="row">
            <div class="col-md-10">

            </div>
            <div class="col-md-2">
                <a asp-action="Index">go to Back</a>
            </div>
        </div>
        <hr />



        <dl class="text-md-left  row">
            <dt class="col-sm-3">
                <span>Program English Name In Single</span>
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.EnglishNameInSingle)
            </dd>

            <dt class="col-sm-3">
                <span>Program English Name In Plural</span>
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.EnglishNameInPlural)
            </dd>

            <dt class="col-sm-3">
                <span>Program Arabic Name In Single</span>
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.ArabicNameInSingle)
            </dd>


            <dt class="col-sm-3">
                <span>Program Arabic Name In Plural</span>
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.ArabicNameInPlural)
            </dd>

            <dt class="col-sm-3">
                <span>Section</span>
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Section.EnglishName)
            </dd>

            <dt class="col-sm-3">
                <span>Program URL For Service</span>
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.URLForService)
            </dd>

            <dt class="col-sm-3">
                <span>Developer Name</span>
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.DevName)
            </dd>


            <dt class="col-sm-3">
                <span>Data</span>
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Date)
            </dd>

        </dl>


        <dl class="col-sm-5">
            <b><a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> </b>
        </dl>



    </div>
    <div>
       
        
    </div>
    </div>

Views/CustomerPrograms/Edit.cshtml
@model Gather_Requirement_Project.Models.CustomerProgram

@{
    ViewData["Title"] = "Edit";
    SelectList SectionsList = new SelectList(ViewBag.portalsList, "ID", "EnglishName");

}
<div class="card ">
    <div class="card-header">
        <h4> <i class="fas fa-table"></i>&nbsp&nbsp Edit Program </h4>
    </div>
    <div class="card-body" style="">
        <div class="row">
            <div class="col-md-10">

            </div>
            <div class="col-md-2">
                <a asp-action="Index">Go to Back</a>
            </div>
        </div>
        <hr />

        <div class="text-md-left row">
            <div class="col-md-6 jumbotron">
                <form asp-action="Edit" asp-controller="CustomerPrograms" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="ID" />

                    <div class="form-group">
                        <label asp-for="EnglishNameInSingle" class="control-label">Program English Name In Single</label>
                        <input asp-for="EnglishNameInSingle" class="form-control" />
                        <span asp-validation-for="EnglishNameInSingle" class="text-danger"></span>
                        <br />

                        <label asp-for="EnglishNameInPlural" class="control-label">Program English Name In Plural</label>
                        <input asp-for="EnglishNameInPlural" class="form-control" />
                        <span asp-validation-for="EnglishNameInPlural" class="text-danger"></span>
                        <br />

                        <label asp-for="EnglishNameInSingle" class="control-label">Program Arabic Name In Single</label>
                        <input asp-for="ArabicNameInSingle" class="form-control" />
                        <span asp-validation-for="ArabicNameInSingle" class="text-danger"></span>
                        <br />

                        <label asp-for="EnglishNameInPlural" class="control-label">Program Arabic Name In Plural</label>
                        <input asp-for="ArabicNameInPlural" class="form-control" />
                        <span asp-validation-for="ArabicNameInPlural" class="text-danger"></span>
                        <br />

                        <label asp-for="URLForService" class="control-label">Program URL For Service</label>
                        <input asp-for="URLForService" class="form-control" />
                        <span asp-validation-for="URLForService" class="text-danger"></span>
                        <br />

                        <div class="form-group">
                            <label asp-for="SectionID" class="control-label">Section</label>
                            <select asp-for="SectionID" class="form-control" asp-items="SectionsList">
                                <option disabled selected>--- SELECT ---</option>
                            </select>
                            <span asp-validation-for="SectionID" class="text-danger"></span>
                        </div>
                        <div>
                            <label asp-for="DevName" class="control-label"><b>Developer Name</b></label>
                            <input asp-for="DevName" class="form-control" />
                            <span asp-validation-for="DevName" class="text-danger"></span>
                        </div>
                        <div>
                            <label asp-for="Date" class="control-label"><b>Date</b></label>
                            <input asp-for="Date" class="form-control" />
                            <span asp-validation-for="Date" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="حفظ التعديل" class="btn btn-primary" />
                    </div>

                </form>
            </div>
        </div>


    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CustomerPrograms/Index.cshtml
@model IEnumerable<Gather_Requirement_Project.Models.CustomerProgram>

    @{
    ViewData["Title"] = "Index";

    int var = 1;
    }




    <div class="container-fluid">
        <div class="card mb-3">
            <div class="card-header ">
                <h4> <i class="fa fa-address-card-o" aria-hidden="true"></i>&nbsp&nbsp Program </h4>

            </div>

            <div class="card-body" style="">
                <div class="row">
                    <div class="col-md-10">
                        <a asp-action="Create">Create New Program</a>
                    </div>
                    <div class="col-md-2">
                    </div>
                </div>
                <hr />

                <table class="table  table-bordered table-hover table-responsive" id="dataTable">
                    <thead>
                        <tr>
                            <th>
                                <span>#</span>
                            </th>

                            <th>
                                <span>Program Name in English</span>
                            </th>
                            <th>
                                <span>Program Name in Arabic</span>
                            </th>
                            <th>
                                <span>Section</span>
                            </th>
                            <th>
                                <span>Developer Name</span>
                            </th>
                            <th>
                                <span>Date</span>
                            </th>
                            <th>
                                <span>Modules</span>
                            </th>
                            <th>
                                <span> </span>
                            </th>

                            <th>
                                <span>SRS</span>
                            </th>
                            <th>
                                <span>json nav</span>
                            </th>
                            <th>
                                <span>Copy IT</span>
                            </th>
                            <th>
                                <span> Classes </span>
                            </th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @var
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.EnglishNameInSingle)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ArabicNameInSingle)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Section.EnglishName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DevName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Date)
                            </td>

                            <td>
                                <a asp-controller="Modules" asp-action="Index" asp-route-programId="@item.ID" class="btn btn-warning"><i class="fa fa-desktop"></i></a>
                            </td>

                            <td>
                                <a asp-action="Edit" asp-route-id="@item.ID" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                                <a asp-action="Details" asp-route-id="@item.ID" class="btn btn-info"><i class="fa fa-book"></i></a>
                                <a asp-action="Delete" asp-route-id="@item.ID" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                                @*<a asp-action="GenerateSQL" asp-route-id="@item.ID" class="btn btn-danger"><i class="fa fa-file"></i></a>*@
                                @*<a asp-action="GenerateJson" asp-route-id="@item.ID" class="btn btn-danger"><i class="fa fa-file"></i></a>*@
                            </td>


                            <td>
                                <a asp-action="GenerateSRS" asp-route-id="@item.ID" class="btn btn-success"><i class="fa fa-hand-pointer-o"></i></a>
                            </td>

                            <td>
                                <a asp-action="GenerateJsonFrontEnd" asp-route-id="@item.ID" class="btn btn-danger"><i class="fa fa-hand-lizard"></i></a>
                            </td>

                            <td>
                                <a asp-action="CopyProgram" asp-route-id="@item.ID" class="btn btn-info"><i class="fa fa-arrow-circle-down"></i></a>
                            </td>
                            <td>
                                <a asp-action="CreateZipFile3" asp-route-Id="@item.ID" class="btn btn-danger"><i class="fa fa-hand-point-down"></i></a>
                            </td>
                        </tr>
                        var = var + 1;
                        }
                    </tbody>
                </table>


            </div>
        </div>
    </div>





    <script>

        //For ref : https://stackoverflow.com/questions/484463/how-do-i-maintain-scroll-position-in-mvc
        $(document).scroll(function () {
            localStorage['page'] = document.URL;
            localStorage['scrollTop'] = $(document).scrollTop();
        });

        $(document).ready(function () {
            if (localStorage['page'] == document.URL) {
                $(document).scrollTop(localStorage['scrollTop']);
            }
        });
    </script>